#!/bin/sh
DIR=$(dirname "$0")
DIR="$(dirname ${DIR}/$(readlink -n $0))"
DIR="$(cd $DIR;pwd)"
if python2 -V 2>/dev/null; then
	exec python2 "$DIR/main.py" python2 "$@"
else
	exec python "$DIR/main.py" python "$@"
fi
